-d /Users/nikolai/FPGA/tang_nano_9k_test/impl/gwsynthesis/tang_nano_9k_test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /Users/nikolai/FPGA/tang_nano_9k_test/src/tang_nano_9k_test.cst
-cfg /Users/nikolai/FPGA/tang_nano_9k_test/impl/pnr/device.cfg
-sdc /Users/nikolai/FPGA/tang_nano_9k_test/src/tang_nano_9k_test.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
